#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генерує master.csv — 333 види, 14 колонок (без key_features_ai).
zones = області через '|'
"""
import csv

HEADER = [
    'scientific_name','common_name_uk','edibility_status',
    'has_photos','in_top20','is_popular',
    'is_poisonous','is_deadly','is_red_listed','rarity_label_uk',
    'in_ai_recognition','has_ai_prompt','legacy_id',
    'zones',
]

# ============================================================
# 133 з фото: (sci, ua, status, top20, popular, legacy)
# zones НЕ тут — воно зливається з distribution.csv
# ============================================================
WITH_PHOTOS = [
    # --- TOP-20 ---
    ("Boletus edulis","Білий гриб","edible",1,1,1),
    ("Lactarius torminosus","Вовнянка рожева","conditionally_edible",1,1,16),
    ("Pleurotus ostreatus","Глива звичайна","edible",1,1,17),
    ("Lactarius resimus","Груздь справжній","conditionally_edible",1,1,8),
    ("Lycoperdon perlatum","Дощовик їстівний","edible",1,1,13),
    ("Boletus luridus","Дубовик звичайний","edible",1,1,14),
    ("Flammulina velutipes","Зимовий опеньок","edible",1,1,""),
    ("Hydnum repandum","Їжовик жовтуватий","edible",1,1,19),
    ("Suillus bovinus","Козляк","edible",1,1,20),
    ("Cantharellus cibarius","Лисичка справжня","edible",1,1,2),
    ("Suillus luteus","Маслюк пізній","edible",1,1,5),
    ("Xerocomus subtomentosus","Моховик зелений","edible",1,1,15),
    ("Armillaria mellea","Опеньок осінній","edible",1,1,6),
    ("Agaricus campestris","Печериця звичайна","edible",1,1,10),
    ("Leccinum scabrum","Підберезник звичайний","edible",1,1,3),
    ("Leccinum aurantiacum","Підосичник","edible",1,1,4),
    ("Imleria badia","Польський гриб","edible",1,1,""),
    ("Lactarius deliciosus","Рижик справжній","edible",1,1,7),
    ("Russula vesca","Сироїжка","edible",1,1,9),
    ("Morchella esculenta","Сморчок звичайний","edible",1,1,11),

    # --- 21-55 популярні ---
    ("Albatrellus confluens","Альбатрел злитий","edible",0,1,""),
    ("Albatrellus ovinus","Альбатрел овечий","edible",0,1,""),
    ("Boletus reticulatus","Білий гриб сітчастий","edible",0,1,""),
    ("Boletus pinophilus","Білий гриб сосновий","edible",0,1,""),
    ("Pleurotus dryinus","Глива дубова","edible",0,1,""),
    ("Pleurotus pulmonarius","Глива легенева","edible",0,1,""),
    ("Macrolepiota procera","Гриб-зонтик великий","edible",0,1,""),
    ("Macrolepiota mastoidea","Гриб-зонтик сосковидний","edible",0,1,""),
    ("Tricholoma equestre","Зеленушка","conditionally_edible",0,1,""),
    ("Hydnum rufescens","Їжовик рудуватий","edible",0,1,""),
    ("Hydnum umbilicatum","Їжовик ямчастий","edible",0,1,""),
    ("Clavulina cristata","Клавуліна гребінчаста","edible",0,1,""),
    ("Clavulina coralloides","Клавуліна зморшкувата","edible",0,1,""),
    ("Cantharellus amethysteus","Лисичка аметистова","edible",0,1,""),
    ("Craterellus lutescens","Лисичка жовта","edible",0,1,""),
    ("Craterellus cinereus","Лисичка сіра","edible",0,1,""),
    ("Craterellus tubaeformis","Лисичка трубчаста","edible",0,1,""),
    ("Cantharellus friesii","Лисичка Фріза","edible",0,1,""),
    ("Suillus placidus","Маслюк білий","edible",0,1,""),
    ("Suillus variegatus","Маслюк жовто-бурий","edible",0,1,""),
    ("Suillus granulatus","Маслюк зернистий","edible",0,1,""),
    ("Suillus grevillei","Маслюк модриновий","edible",0,1,""),
    ("Xerocomellus chrysenteron","Моховик тріщинуватий","edible",0,1,""),
    ("Amanita excelsa","Мухомор високий","conditionally_edible",0,1,""),
    ("Amanita rubescens","Мухомор червоніючий","conditionally_edible",0,1,""),
    ("Amanita crocea","Мухомор шафрановий","edible",0,1,""),
    ("Kuehneromyces mutabilis","Опеньок літній","edible",0,1,""),
    ("Armillaria ostoyae","Опеньок темний","edible",0,1,""),
    ("Leccinellum pseudoscabrum","Підберезник грабовий","edible",0,1,""),
    ("Leccinum versipelle","Підберезник жовто-бурий","edible",0,1,""),
    ("Leccinum variicolor","Підберезник різнокольоровий","edible",0,1,""),
    ("Leccinum duriusculum","Підберезник тополевий","edible",0,1,""),
    ("Russula delica","Підгруздь","edible",0,1,""),
    ("Leccinum albostipitatum","Підосичник білоніжковий","edible",0,1,""),
    ("Amanita fulva","Поплавок жовто-коричневий","edible",0,1,""),

    # --- 56-99: решта з фото (не популярні, не ЧК, не отруйні) ---
    ("Amanita vaginata","Поплавок сірий","edible",0,0,""),
    ("Ramaria botrytis","Рамарія гроновидна","edible",0,0,""),
    ("Lactarius deterrimus","Рижик ялиновий","edible",0,0,""),
    ("Lactarius salmonicolor","Рижик ялицевий","edible",0,0,""),
    ("Tricholoma terreum","Рядовка землиста","edible",0,0,""),
    ("Lepista personata","Рядовка ліловонога","edible",0,0,""),
    ("Calocybe gambosa","Рядовка майська","edible",0,0,""),
    ("Tricholoma portentosum","Рядовка сіра","edible",0,0,""),
    ("Lepista nuda","Рядовка фіолетова","edible",0,0,""),
    ("Russula xerampelina","Сироїжка буро-червона","edible",0,0,""),
    ("Russula virescens","Сироїжка зелена","edible",0,0,""),
    ("Russula cyanoxantha","Сироїжка синьо-жовта","edible",0,0,""),
    ("Russula foetens","Сироїжка смердюча","inedible",0,0,""),
    ("Lactarius vellereus","Скрипиця","conditionally_edible",0,0,""),
    ("Polyporus squamosus","Трутовик лускатий","edible",0,0,""),
    ("Laetiporus sulphureus","Трутовик сірчано-жовтий","edible",0,0,""),
    ("Lactarius quietus","Хрящ-молочник дубовий","edible",0,0,""),
    ("Lactifluus volemus","Хрящ-молочник їстівний","edible",0,0,""),
    ("Lactarius piperatus","Хрящ-молочник перцевий","conditionally_edible",0,0,""),
    ("Lactarius subdulcis","Хрящ-молочник солодкуватий","edible",0,0,""),

    # --- 100-143: 44 ЧЕРВОНОКНИЖНИХ ---
    ("Boletus aereus","Боровик бронзовий","edible",0,0,""),
    ("Rubroboletus lupinus","Боровик вовчий","inedible",0,0,""),
    ("Butyriboletus appendiculatus","Боровик дівочий","edible",0,0,""),
    ("Butyriboletus regius","Боровик королівський","edible",0,0,""),
    ("Butyriboletus subappendiculatus","Боровик напівапендикулярний","edible",0,0,""),
    ("Butyriboletus fuscoroseus","Боровик рожево-бурий","edible",0,0,""),
    ("Rubroboletus rhodoxanthus","Боровик рожево-жовтий","poisonous",0,0,""),
    ("Rubroboletus satanas","Боровик сатанинський","poisonous",0,0,""),
    ("Butyriboletus fechtneri","Боровик Фехтнера","edible",0,0,""),
    ("Rubroboletus rubrosanguineus","Боровик червоно-кривавий","poisonous",0,0,""),
    ("Phallus duplicatus","Веселка подвоєна","inedible",0,0,""),
    ("Hemileccinum depilatum","Гемілецінум безволосий","edible",0,0,""),
    ("Hericium erinaceus","Герицій їжаковий","edible",0,0,""),
    ("Hericium coralloides","Герицій кораловий","inedible",0,0,""),
    ("Hygrocybe calyptriformis","Гігроцибе ковпакоподібна","inedible",0,0,""),
    ("Gomphus clavatus","Гомф булавоподібний","edible",0,0,""),
    ("Grifola frondosa","Грифола листувата","edible",0,0,""),
    ("Morchella steppicola","Зморшок степовий","edible",0,0,""),
    ("Pseudocolus fusiformis","Кальмарник веретеноподібний","inedible",0,0,""),
    ("Catathelasma imperiale","Катателазма царська","edible",0,0,""),
    ("Anthurus archeri","Квітохвісник Арчера","inedible",0,0,""),
    ("Clavariadelphus pistillaris","Клаваріадельф товкачиковий","inedible",0,0,""),
    ("Lyophyllum favrei","Ліофіл Фавре","inedible",0,0,""),
    ("Helvella monachella","Лопатевик чорний","inedible",0,0,""),
    ("Suillus plorans","Маслюк кедровий","edible",0,0,""),
    ("Myriostoma coliforme","Міріостома шийкова","inedible",0,0,""),
    ("Boletus parasiticus","Моховик паразитний","inedible",0,0,""),
    ("Amanita caesarea","Мухомор цезарів","edible",0,0,""),
    ("Amanita strobiliformis","Мухомор щетинистий","conditionally_edible",0,0,""),
    ("Chalciporus rubinus","Решетняк карміново-червоний","inedible",0,0,""),
    ("Clathrus ruber","Решіточник червоний","inedible",0,0,""),
    ("Tricholoma colossus","Рядовка величезна","inedible",0,0,""),
    ("Tricholoma focale","Рядовка опеньковидна","inedible",0,0,""),
    ("Sarcosoma globosum","Саркосома куляста","inedible",0,0,""),
    ("Russula turci","Сироїжка синювата","edible",0,0,""),
    ("Scleroderma geaster","Склеродерма зірчаста","inedible",0,0,""),
    ("Sparassis crispa","Спарасис кучерявий","edible",0,0,""),
    ("Polyporus umbellatus","Трутовик зонтичний","edible",0,0,""),
    ("Tuber aestivum","Трюфель літній","edible",0,0,""),
    ("Phellorinia herculeana","Фелоринія геркулесова","inedible",0,0,""),
    ("Phaeolepiota aurea","Феолепіота золотиста","inedible",0,0,""),
    ("Phylloporus pelletieri","Філопор рожево-золотистий","edible",0,0,""),
    ("Lactarius lignyotus","Хрящ-молочник чорний","edible",0,0,""),
    ("Strobilomyces strobilaceus","Шишкогриб лускатий","inedible",0,0,""),

    # --- 144-157: 14 отруйних і смертельно отруйних ---
    ("Amanita muscaria","Мухомор червоний","poisonous",0,0,""),
    ("Amanita pantherina","Мухомор пантерний","poisonous",0,0,""),
    ("Amanita phalloides","Бліда поганка","deadly_poisonous",0,0,""),
    ("Amanita verna","Мухомор весняний","deadly_poisonous",0,0,""),
    ("Amanita virosa","Мухомор смердючий","deadly_poisonous",0,0,""),
    ("Clitocybe candicans","Говорушка білувата","poisonous",0,0,""),
    ("Clitocybe dealbata","Говорушка воскова","poisonous",0,0,""),
    ("Entoloma sinuatum","Ентолома отруйна","poisonous",0,0,""),
    ("Galerina marginata","Галерина облямована","deadly_poisonous",0,0,""),
    ("Gyromitra esculenta","Строчок звичайний","deadly_poisonous",0,0,""),
    ("Hygrophoropsis aurantiaca","Лисичка несправжня","poisonous",0,0,""),
    ("Inocybe erubescens","Волоконниця червоніюча","poisonous",0,0,""),
    ("Inocybe geophylla","Іноцибе звичайний","poisonous",0,0,""),
    ("Paxillus involutus","Свинуха тонка","poisonous",0,0,""),
]

assert len(WITH_PHOTOS) == 133, f"Очікується 133, отримано {len(WITH_PHOTOS)}"

# ============================================================
# 200 без фото: (sci, ua, status)
# zones — поки НЕ заповнюємо (окрема ітерація)
# ============================================================
WITHOUT_PHOTOS = [
    ("Agaricus arvensis","Печериця польова","edible"),
    ("Agaricus silvaticus","Печериця лісова","edible"),
    ("Agaricus xanthodermus","Печериця жовтошкіра","poisonous"),
    ("Amanita citrina","Мухомор цитриновий","poisonous"),
    ("Amanita porphyria","Мухомор пурпуровий","poisonous"),
    ("Amanita vittadinii","Мухомор Віттадіні","poisonous"),
    ("Amanita echinocephala","Мухомор колючоголовий","inedible"),
    ("Boletus calopus","Боровик неїстівний","inedible"),
    ("Boletus impolitus","Боровик жовтий","edible"),
    ("Boletus queletii","Боровик Келета","conditionally_edible"),
    ("Boletus erythropus","Боровик зернистоногий","conditionally_edible"),
    ("Boletus purpureus","Боровик пурпуровий","poisonous"),
    ("Gyroporus castaneus","Гіропор каштановий","edible"),
    ("Gyroporus cyanescens","Гіропор синіючий","edible"),
    ("Gyrodon lividus","Гіродон сизуватий","edible"),
    ("Boletinus cavipes","Болетин порожньоногий","edible"),
    ("Tylopilus felleus","Тилопіл жовчний","inedible"),
    ("Porphyrellus pseudoscaber","Порфірел пурпуровоспоровий","inedible"),
    ("Gomphidius glutinosus","Мокруха клейка","edible"),
    ("Gomphidius roseus","Мокруха рожева","edible"),
    ("Gomphidius rutilus","Мокруха слизька","edible"),
    ("Gomphidius maculatus","Мокруха плямиста","edible"),
    ("Paxillus atrotomentosus","Паксил чорноповстистий","conditionally_edible"),
    ("Paxillus panuoides","Паксил вохряно-рудий","conditionally_edible"),
    ("Ripartites tricholoma","Рипартитес рядовковидний","edible"),
    ("Ripartites helomorpha","Рипартит геломорфний","edible"),
    ("Lactarius sanguifluus","Рижик червоний","edible"),
    ("Lactarius semisanguifluus","Хрящ-молочник зеленувато-червоний","edible"),
    ("Lactarius fuliginosus","Хрящ-молочник сірий","conditionally_edible"),
    ("Lactarius acris","Хрящ-молочник червоніючий","inedible"),
    ("Lactarius chrysorrheus","Хрящ-молочник золотисто-жовтий","inedible"),
    ("Lactarius theiogalus","Хрящ-молочник болотний","inedible"),
    ("Lactarius hepaticus","Хрящ-молочник оранжево-пластинчастий","inedible"),
    ("Lactarius scrobiculatus","Хрящ-молочник жовтий","conditionally_edible"),
    ("Lactarius trivialis","Хрящ-молочник сизий","conditionally_edible"),
    ("Lactarius musteus","Хрящ-молочник моховий","inedible"),
    ("Lactarius rubrocinctus","Хрящ-молочник рубчастий","inedible"),
    ("Lactarius glaucescens","Хрящ-молочник зеленіючий","edible"),
    ("Lactarius blennius","Хрящ-молочник сіро-зелений","edible"),
    ("Lactarius vietus","Хрящ-молочник бляклий","conditionally_edible"),
    ("Lactarius uvidus","Хрящ-молочник ліловіючий","conditionally_edible"),
    ("Lactarius violascens","Хрящ-молочник фіолетовий","inedible"),
    ("Lactarius aspideus","Хрящ-молочник жовтуватий ліловіючий","inedible"),
    ("Lactarius repraesentaneus","Хрящ-молочник золотисто-жовтий ліловіючий","conditionally_edible"),
    ("Lactarius pubescens","Хрящ-молочник пухнастий","conditionally_edible"),
    ("Lactarius controversus","Хрящ-молочник осиковий","conditionally_edible"),
    ("Lactarius turpis","Хрящ-молочник оливково-чорний","conditionally_edible"),
    ("Lactarius mammosus","Хрящ-молочник сосочковий","inedible"),
    ("Lactarius flexuosus","Хрящ-молочник сіро-лілуватий","conditionally_edible"),
    ("Lactarius spinosulus","Хрящ-молочник шипастий","inedible"),
    ("Russula albonigra","Сироїжка біло-чорна","conditionally_edible"),
    ("Russula nigricans","Сироїжка чорніюча","conditionally_edible"),
    ("Russula densifolia","Сироїжка густопластинчаста","inedible"),
    ("Russula adusta","Сироїжка чорна","conditionally_edible"),
    ("Russula decolorans","Сироїжка вицвітаюча","edible"),
    ("Russula obscura","Сироїжка темна","edible"),
    ("Russula claroflava","Сироїжка світло-жовта","edible"),
    ("Russula ochroleuca","Сироїжка вохряно-жовта","inedible"),
    ("Russula puellaris","Сироїжка дівоча","edible"),
    ("Russula viscida","Сироїжка слизька","edible"),
    ("Russula lilacea","Сироїжка лілова","edible"),
    ("Russula pulchella","Сироїжка гарна","edible"),
    ("Russula olivacea","Сироїжка оливково-зелена","edible"),
    ("Russula atropurpurea","Сироїжка чорно-пурпурова","edible"),
    ("Russula lutea","Сироїжка червоно-жовта","edible"),
    ("Russula mustelina","Сироїжка коричнева","edible"),
    ("Russula mollis","Сироїжка м'яка","edible"),
    ("Russula aeruginosa","Сироїжка зелена велика","edible"),
    ("Russula amoena","Сироїжка зерниста","edible"),
    ("Russula heterophylla","Сироїжка різнопластинчаста","edible"),
    ("Russula grisea","Сироїжка сіра","edible"),
    ("Russula roseipes","Сироїжка рожевонога","edible"),
    ("Russula brunneoviolacea","Сироїжка коричнево-лілова","edible"),
    ("Russula melliolens","Сироїжка медова","edible"),
    ("Russula aurata","Сироїжка золотиста","edible"),
    ("Russula paludosa","Сироїжка болотяна","edible"),
    ("Russula curtipes","Сироїжка коротконога","edible"),
    ("Russula alutacea","Сироїжка зелено-червона","edible"),
    ("Russula integra","Сироїжка бездоганна","edible"),
    ("Russula fellea","Сироїжка жовта","inedible"),
    ("Russula farinipes","Сироїжка валуєвидна","inedible"),
    ("Russula consobrina","Сироїжка сірувато-бура","inedible"),
    ("Russula pectinata","Сироїжка гребінчаста","inedible"),
    ("Russula emetica","Сироїжка блювотна","poisonous"),
    ("Russula luteotacta","Сироїжка жовтіюча","inedible"),
    ("Russula fragilis","Сироїжка крихка","inedible"),
    ("Russula violacea","Сироїжка фіолетова","inedible"),
    ("Russula versicolor","Сироїжка різнобарвна","edible"),
    ("Russula firmula","Сироїжка лілова","inedible"),
    ("Russula maculata","Сироїжка плямиста","inedible"),
    ("Russula rubra","Сироїжка червона","inedible"),
    ("Russula sanguinea","Сироїжка криваво-червона","inedible"),
    ("Russula badia","Сироїжка пурпурово-коричнева","inedible"),
    ("Russula sardonia","Сироїжка темно-фіолетова","inedible"),
    ("Russula queletii","Сироїжка Келета","inedible"),
    ("Russula rosea","Сироїжка рожева","conditionally_edible"),
    ("Russula pseudointegra","Сироїжка рум'яна","conditionally_edible"),
    ("Russula caerulea","Сироїжка лазурова","edible"),
    ("Russula nauseosa","Сироїжка бридка","inedible"),
    ("Tricholoma album","Рядовка біла","poisonous"),
    ("Tricholoma sulphureum","Рядовка сірчано-жовта","poisonous"),
    ("Tricholoma virgatum","Рядовка волокниста","poisonous"),
    ("Tricholoma vaccinum","Рядовка рудувато-червона","inedible"),
    ("Tricholoma imbricatum","Рядовка черепичаста","inedible"),
    ("Tricholoma pessundatum","Рядовка згубна","poisonous"),
    ("Tricholoma populinum","Рядовка тополева","edible"),
    ("Tricholoma saponaceum","Рядовка сіра","inedible"),
    ("Tricholoma sejunctum","Рядовка відокремлена","inedible"),
    ("Tricholoma orirubens","Рядовка червоніюча","inedible"),
    ("Clitocybe nebularis","Говорушка сіра","conditionally_edible"),
    ("Clitocybe geotropa","Говорушка руда","edible"),
    ("Clitocybe gigantea","Говорушка гігантська","edible"),
    ("Clitocybe odora","Говорушка ароматна","edible"),
    ("Clitocybe clavipes","Говорушка булавовиднонога","inedible"),
    ("Clitocybe infundibuliformis","Говорушка лійковидна","edible"),
    ("Clitocybe rivulosa","Говорушка червонувата","poisonous"),
    ("Clitocybe phyllophila","Говорушка листолюбна","poisonous"),
    ("Clitocybe suaveolens","Говорушка запашна","edible"),
    ("Clitocybe brumalis","Говорушка зимова","inedible"),
    ("Collybia dryophila","Колібія лісолюбна","edible"),
    ("Collybia peronata","Колібія обгорнута","inedible"),
    ("Collybia confluens","Колібія численна","edible"),
    ("Collybia maculata","Колібія плямиста","inedible"),
    ("Collybia butyracea","Колібія рудувато-сіра","edible"),
    ("Collybia fusipes","Колібія веретенонога","conditionally_edible"),
    ("Mycena pura","Міцена чиста","poisonous"),
    ("Mycena galericulata","Міцена ковпаковидна","inedible"),
    ("Mycena polygramma","Міцена штрихувата","inedible"),
    ("Mycena haematopus","Міцена кривавонога","inedible"),
    ("Mycena rosella","Міцена рожева","inedible"),
    ("Mycena epipterygia","Міцена слизька","inedible"),
    ("Mycena inclinata","Міцена нахилена","inedible"),
    ("Mycena aetites","Міцена лужна","inedible"),
    ("Mycena galopus","Міцена білосокова","inedible"),
    ("Mycena sanguinolenta","Міцена кривавоплямиста","inedible"),
    ("Marasmius oreades","Опеньок луговий","edible"),
    ("Marasmius alliaceus","Часничник великий","edible"),
    ("Marasmius scorodonius","Часничник дрібний","edible"),
    ("Marasmius prasiosmus","Маразмій вицвітаючий","edible"),
    ("Marasmius rotula","Маразмій колесовидний","inedible"),
    ("Marasmius epiphyllus","Маразмій листовий","inedible"),
    ("Entoloma clypeatum","Ентолома щитовидна","edible"),
    ("Entoloma rhodopolium","Ентолома рожево-сива","poisonous"),
    ("Entoloma nidorosum","Ентолома смердюча","poisonous"),
    ("Entoloma sericeum","Ентолома шовковиста","edible"),
    ("Entoloma jubatum","Ентолома волохата","edible"),
    ("Entoloma aprile","Ентолома квітнева","poisonous"),
    ("Pluteus cervinus","Плютей бурий","edible"),
    ("Pluteus salicinus","Плютей вербовий","edible"),
    ("Hygrophorus eburneus","Гігрофор жовтувато-білий","edible"),
    ("Hygrophorus chrysodon","Гігрофор золотистий","edible"),
    ("Hygrophorus hypothejus","Гігрофор пізній","edible"),
    ("Hygrophorus olivaceoalbus","Гігрофор оливково-білий","edible"),
    ("Hygrophorus russula","Гігрофор сироїжковидний","edible"),
    ("Hygrophorus pratensis","Гігрофор луговий","edible"),
    ("Hygrophorus nemoreus","Гігрофор дібровний","edible"),
    ("Hygrophorus camarophyllus","Гігрофор козячий","edible"),
    ("Hygrophorus virgineus","Гігрофор дівочий","edible"),
    ("Hygrophorus fornicatus","Гігрофор склепистий","edible"),
    ("Hygrophorus foetens","Гігрофор смердючий","inedible"),
    ("Hygrophorus capreolarius","Гігрофор винно-червоний","edible"),
    ("Hygrophorus marzuolus","Гігрофор ранній","edible"),
    ("Hygrophorus penarius","Гігрофор їстівний","edible"),
    ("Hygrophorus lucorum","Гігрофор модриновий","edible"),
    ("Coprinus comatus","Гнойовик білий","edible"),
    ("Coprinus atramentarius","Гнойовик сірий","conditionally_edible"),
    ("Coprinus micaceus","Гнойовик мерехтливий","edible"),
    ("Coprinus radians","Гнойовик променистий","inedible"),
    ("Coprinus lagopus","Гнойовик заяча лапа","inedible"),
    ("Hypholoma fasciculare","Опеньок сірчано-жовтий","poisonous"),
    ("Hypholoma capnoides","Опеньок димчастий","edible"),
    ("Stropharia aeruginosa","Строфарія синьо-зелена","inedible"),
    ("Pholiota squarrosa","Лускатка луската","conditionally_edible"),
    ("Pholiota aurivella","Лускатка золотиста","edible"),
    ("Cortinarius violaceus","Павутинник фіолетовий","edible"),
    ("Cortinarius armillatus","Павутинник браслетний","edible"),
    ("Cortinarius triumphans","Павутинник тріумфальний","edible"),
    ("Inocybe geophylla","Волоконниця земляна","poisonous"),
    ("Inocybe fastigiata","Волоконниця рівновершинна","poisonous"),
    ("Macrolepiota rhacodes","Гриб-зонтик червоніючий","edible"),
    ("Lepiota clypeolaria","Лепіота щитоносна","inedible"),
    ("Lepiota cristata","Лепіота гребінчаста","poisonous"),
    ("Lepiota felina","Лепіота котяча","inedible"),
    ("Lepiota lilacea","Лепіота лілова","inedible"),
    ("Lyophyllum decastes","Ліофіл груповий","edible"),
    ("Lyophyllum connatum","Ліофіл зрослий","edible"),
    ("Lyophyllum ulmarium","Ліофіл в'язовий","edible"),
    ("Lyophyllum loricatum","Ліофіл панцирний","edible"),
    ("Lyophyllum immundum","Ліофіл чорніючий","edible"),
    ("Pleurotus cornucopiae","Плеврот рясний","edible"),
    ("Pleurotus calyptratus","Плеврот ковпаковидний","edible"),
    ("Pleurotus eryngii","Плеврот миколайчиковий","edible"),
    ("Lentinus tigrinus","Лентин тигровий","edible"),
    ("Lentinus cyathiformis","Лентин бокаловидний","edible"),
    ("Lentinus lepideus","Лентин лускатий","edible"),
    ("Schizophyllum commune","Схізофіл звичайний","inedible"),
    ("Volvariella speciosa","Вольварієла прекрасна","edible"),
    ("Volvariella bombycina","Вольварієла надеревна","edible"),
    ("Pluteus atromarginatus","Плютей чорнооторочений","edible"),
]

assert len(WITHOUT_PHOTOS) == 200, f"Очікується 200, отримано {len(WITHOUT_PHOTOS)}"

# ============================================================
# Додаткові множини
# ============================================================
DEADLY_SPECIES = {
    'Amanita phalloides','Amanita verna','Amanita virosa',
    'Galerina marginata','Gyromitra esculenta',
}

RARITY_LABELS = {
    'Boletus aereus':'Рідкісний вид',
    'Rubroboletus lupinus':'Вразливий вид',
    'Butyriboletus appendiculatus':'Рідкісний вид',
    'Butyriboletus regius':'Зникаючий вид',
    'Butyriboletus subappendiculatus':'Рідкісний вид',
    'Butyriboletus fuscoroseus':'Рідкісний вид',
    'Rubroboletus rhodoxanthus':'Вразливий вид',
    'Rubroboletus satanas':'Рідкісний вид',
    'Butyriboletus fechtneri':'Зникаючий вид',
    'Rubroboletus rubrosanguineus':'Вразливий вид',
    'Phallus duplicatus':'Рідкісний вид',
    'Hemileccinum depilatum':'Рідкісний вид',
    'Hericium erinaceus':'Вразливий вид',
    'Hericium coralloides':'Вразливий вид',
    'Hygrocybe calyptriformis':'Рідкісний вид',
    'Gomphus clavatus':'Вразливий вид',
    'Grifola frondosa':'Рідкісний вид',
    'Morchella steppicola':'Зникаючий вид',
    'Pseudocolus fusiformis':'Рідкісний вид',
    'Catathelasma imperiale':'Рідкісний вид',
    'Anthurus archeri':'Рідкісний вид',
    'Clavariadelphus pistillaris':'Рідкісний вид',
    'Lyophyllum favrei':'На межі зникнення',
    'Helvella monachella':'Рідкісний вид',
    'Suillus plorans':'Рідкісний вид',
    'Myriostoma coliforme':'Вразливий вид',
    'Boletus parasiticus':'Рідкісний вид',
    'Amanita caesarea':'Зникаючий вид',
    'Amanita strobiliformis':'Рідкісний вид',
    'Chalciporus rubinus':'Рідкісний вид',
    'Clathrus ruber':'Рідкісний вид',
    'Tricholoma colossus':'Рідкісний вид',
    'Tricholoma focale':'Вразливий вид',
    'Sarcosoma globosum':'Вразливий вид',
    'Russula turci':'Рідкісний вид',
    'Scleroderma geaster':'Рідкісний вид',
    'Sparassis crispa':'Вразливий вид',
    'Polyporus umbellatus':'Рідкісний вид',
    'Tuber aestivum':'Зникаючий вид',
    'Phellorinia herculeana':'На межі зникнення',
    'Phaeolepiota aurea':'Рідкісний вид',
    'Phylloporus pelletieri':'Рідкісний вид',
    'Lactarius lignyotus':'Рідкісний вид',
    'Strobilomyces strobilaceus':'Рідкісний вид',
}

# ============================================================
# Читаємо distribution.csv (75 рядків)
# ============================================================
dist = {}
try:
    with open('distribution.csv', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            dist[row['scientific_name']] = row['zones']
except FileNotFoundError:
    print("⚠ distribution.csv не знайдено — zones будуть порожні")

# ============================================================
# Генерація
# ============================================================
with open('master.csv', 'w', encoding='utf-8', newline='') as f:
    w = csv.writer(f)
    w.writerow(HEADER)

    # --- 133 з фото ---
    for sci, ua, status, top20, popular, legacy in WITH_PHOTOS:
        is_poison = status in ('poisonous','deadly_poisonous')
        is_deadly = sci in DEADLY_SPECIES
        is_red = sci in RARITY_LABELS
        rarity = RARITY_LABELS.get(sci, '')
        zones = dist.get(sci, '')     # ← області через |

        w.writerow([
            sci, ua, status,
            1, top20, popular,
            1 if is_poison else 0,
            1 if is_deadly else 0,
            1 if is_red else 0,
            rarity,
            1, 1,                       # in_ai_recognition, has_ai_prompt
            legacy,
            zones,
        ])

    # --- 200 без фото ---
    for sci, ua, status in WITHOUT_PHOTOS:
        is_poison = status in ('poisonous','deadly_poisonous')
        is_deadly = sci in DEADLY_SPECIES

        w.writerow([
            sci, ua, status,
            0, 0, 0,
            1 if is_poison else 0,
            1 if is_deadly else 0,
            0, '',
            0, 1,                       # in_ai_recognition=0, has_ai_prompt=1
            '',
            '',                         # zones — окрема ітерація
        ])

print("✓ master.csv: 133 + 200 = 333 рядки")
print(f"  ▪ zones заповнено для {len(dist)} видів")
print(f"  ▪ 44 ЧК, 14 отруйних, 5 смертельно отруйних")
